$(document).ready(function(){
  $(".off").click(function(){
    $(this).toggleClass("on");
  });
  $(".on").click(function(){
    $(this).removeClass("on").addClass("on-loud");
  });
  $(".on-loud").click(function(){
    $(this).removeClass("on-loud").addClass("off");
  });
});
